04 cli grep
vsgol/hse-sd-3 pull request #15
Opened 2022-02-10 19:41 UTC by DT6A

2022-03-06 16:58 UTC, yurii-litvinov requested changes
По диаграмме:
- Отсутствие навигабельности у ассоциации явно (как у вас, крестиком) обычно не рисуют. Рисуют только когда хочется подчеркнуть, что ходить в обратную сторону точно никак нельзя. Если навигаьельность у одного конца указана, а у другого нет, подразумевается его отсутствие (хотя формально вы правы).
- Наследование стоит рисовать в виде дерева сверху вниз, а не "солнышком". Это делает диаграмму более читаемой.
- Вместо str стоило использовать стандартный тип string из UML
- Lex и YaccParser надо было изобразить на диаграмме, скорее всего, как классы без полей и методов (типа они есть, но не важны). Иначе это какие-то необъявленные идентификаторы.
- `str[]` UML не умеет. Умеет `str[*]`.
- Команды у вас никак не связаны с остальной системой, хотя Command Factory их, скорее всего, производит, а другие классы используют. Это надо показать отношением зависимости. Вообще, классы без визуальных связей настораживают всегда.

По grep-у:
- Пропущенный числовой параметр для `-A` убивает шелл.
- На отрицательный параметр не ругается, хотя можно было бы, и это было бы хорошо для пользователя.

В общем, надо поправить

2022-03-06 16:58 UTC, yurii-litvinov commented on CLI/README.md
> +* Plac. Позволяет генерировать парсер аргументов на основе сигнатуры функций и декораторв. Для нашей ситуации не очень подходит или надо лезть глубже в документацию чтобы понять как ее заиспользовать
```suggestion
* Plac. Позволяет генерировать парсер аргументов на основе сигнатуры функций и декораторов. Для нашей ситуации не очень подходит или надо лезть глубже в документацию чтобы понять как ее заиспользовать без излишеств.
```

2022-03-06 16:58 UTC, yurii-litvinov commented on CLI/README.md
> +* Click. В плане синтаксиса так же похожа на Argparse, но аналогично Plac регулируется с помощью декоратора функции, которую планируется запускать, что опять же некоторая проблема в нашем случае. Но
Если уж совсем по-хорошему делать, надо ещё методику и критерии поиска. Типа как искали и по каким критериям отбирали. Но так тоже ок.

2022-03-06 16:58 UTC, yurii-litvinov commented on CLI/cli_module/string_processor/parser/command/test_command.py
> +        ]:
А Питон каким-то стандартным образом не умеет в Data-Driven тесты? А то с точки зрения тестовой системы это один тест, что не очень с точки зрения error reporting-а.

2022-03-07 13:28 UTC, DT6A commented on CLI/cli_module/string_processor/parser/command/test_command.py
> +        ]:
Кажется стандартным образом не очень умеет(

2022-04-17 17:52 UTC, yurii-litvinov requested changes
- Про крестики у стрелок на диаграмме не поправили, хотя формально так тоже можно, так что не придираюсь.
- 0..* — это то же самое, что просто *
- Было бы неплохо побольше зависимостей от команд
- И скомпоновано на мой вкус неудачно — всё в одну линию. Теряете двумерность и возможность визуальной группировкой классов показать степень их архитектурной близости.

`grep -A` всё ещё убивает шелл. Так что это всё-таки надо доисправлять, но в остальном всё ок.

2022-04-17 17:52 UTC, yurii-litvinov commented on CLI/cli_module/string_processor/parser/command/test_command.py
> +        ]:
Увы. Ну ладно

2022-04-17 20:52 UTC, DT6A commented
@yurii-litvinov grep поправлен

2022-04-18 09:48 UTC, yurii-litvinov approved these changes
👍

2022-06-21 19:53 UTC, merged